---
- hosts: all
  gather_facts: no

  vars:
    jsondata: "{{ lookup('file','sample_topo.json')|from_json }}"
    jsonmetadata: "{{ lookup('file','sample_metadata.json')|from_json }}"
    project_name: "test_project"
    #project_directory: "/some_project_folder"
    inventory_template_src: "/Users/josesanchez/Qsync/OSI/NetworkCI/json_dict/hosts.j2"
    inventory_template_dest: "/Users/josesanchez/Qsync/OSI/NetworkCI/json_dict/{{project_name}}/test_host.ini"
    hostvar_template_src:
    hostvar_template_dest:

  tasks:
##///create destination project directory
      - name: Creating Project Directory
        file:
          path: ./{{project_name}}
          state: directory
        delegate_to: localhost

##///flip json to dicts and lists
      - name: Iterate Json -  Device
        set_fact:
          name_item: "{{item.Name}}"
          os_item:  "{{item.NodeType}}"
          id_item: "{{item.FakeID}}"
        loop: "{{jsondata.Routers}}"
        register: device_results

      - name: Create Fact List - Device
        set_fact:
          name: "{{ device_results.results | map(attribute='ansible_facts.name_item') | list }}"
          os: "{{ device_results.results | map(attribute='ansible_facts.os_item') | list }}"
          Did: "{{ device_results.results | map(attribute='ansible_facts.id_item') | list }}"

    ##  - name: Verify vars - Device
    ##    debug: var=name ###or whatever for testing

      - name: Iterate Json -  Links
        set_fact:
          src_item: "{{item.Source}}"
          dest_item:  "{{item.Target}}"
          id_item: "{{item.FakeID}}"
        loop: "{{jsondata.Links}}"
        register: link_results

      - name: Create Fact List - Links
        set_fact:
          src: "{{ link_results.results | map(attribute='ansible_facts.src_item') | list }}"
          dest: "{{ link_results.results | map(attribute='ansible_facts.dest_item') | list }}"
          Lid: "{{ link_results.results | map(attribute='ansible_facts.id_item') | list }}"

    ##  - name: Verify vars - Links
    ##    debug: var=name ###or whatever for testing

      - name: Iterate Json -  Metadata
        set_fact:
          mname_item: "{{item.hostname}}"
          mip_item:  "{{item.ip}}"
          mos_item: "{{item.os}}"
          musername_item: "{{item.username}}"
          mpassword_item: "{{item.password}}"
        loop: "{{jsonmetadata.hosts}}"
        register: meta_results

      - name: Create Fact List - Metadata
        set_fact:
          mname: "{{ meta_results.results | map(attribute='ansible_facts.mname_item') | list }}"
          mip: "{{ meta_results.results | map(attribute='ansible_facts.mip_item') | list }}"
          mos: "{{ meta_results.results | map(attribute='ansible_facts.mos_item') | list }}"
          musername: "{{ meta_results.results | map(attribute='ansible_facts.musername_item') | list }}"
          mpassword: "{{ meta_results.results | map(attribute='ansible_facts.mpassword_item') | list }}"

      #- name: Verify vars - Metadata
      #  debug: var=mname ###or whatever for testing

##///some kinda jinja templating to generate inventory file
      - name: Generate Inventory File
        template: src={{inventory_template_src}} dest={{inventory_template_dest}}
        delegate_to: localhost

##///some kinda jinja templating to generate host_var files and site.yml playbook
      - name: Creating directories
        file:
          path: ./{{project_name}}/{{item}}
          state: directory
        delegate_to: localhost
        with_items:
          - roles
          - host_vars

#      - name: Generate Host_Var files
#        template: src={{hostvar_template_src}} dest={{hostvar_template_dest}}
#        delegate_to: localhost
#        loop:


##///some kinda jinja templating for configuring interface descriptions
