---

      - name: csr1 config
        ios_config:
           src: ./files/csr1_config.cfg
        when: inventory_hostname == "csr1"

      - name: csr2 config
        ios_config:
           src: ./files/csr2_config.cfg
        when: inventory_hostname == "csr2"

      - name: nxosv1 config
        ios_config:
           src: ./files/nxos1_config.cfg
        when: inventory_hostname == "nxosv1"

      - name: nxosv2 config
        ios_config:
           src: ./files/nxos2_config.cfg
        when: inventory_hostname == "nxosv2"

      - name: debug
        debug: msg={{inventory_hostname}}
